version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo-db-prod
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    container_name: cocktail-app-backend
    ports:
      - "80:5000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_ROOT_USER=${MONGO_ROOT_USER}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - JWT_SECRET=${JWT_SECRET}
      
networks:
  default:
    external:
      name: cocktail-app-network

volumes:
  mongo-data:
