FROM node:20-alpine

# Copy app source code
RUN mkdir -p /home/app
COPY . /home/app

# Create and change to the app directory.
WORKDIR /home/app

COPY package*.json ./
RUN npm install

EXPOSE 80

CMD ["npm", "start"]
